version: '3.9'

services:
  postgres:
    image: postgres
    build: db
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
       compose-network:
        aliases:
          - postgres

  backend:
    build: backend
    container_name: backend
    restart: on-failure
    command: ["./start.sh"]
    environment: 
       DB_CONNECTION: "host='postgres' dbname='postgres' user='postgres' password='postgres'"
       HOST: "0.0.0.0"
       PORT: "5000"
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
        compose-network:
          aliases:
            - backend

  frontend:
    build: frontend
    container_name: frontend
    environment:
      BACKEND_URL: "http://localhost:5000"
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - compose-network  


networks: 
  compose-network:
    driver: bridge