# syntax=docker/dockerfile:1
FROM python:3.7-alpine
WORKDIR /code
ENV FLASK_APP=main.py
ENV FLASK_RUN_HOST=0.0.0.0
COPY requirements.txt requirements.txt
RUN \
 apk add --no-cache postgresql-libs && \
 apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
 python3 -m pip install -r requirements.txt --no-cache-dir && \
 apk --purge del .build-deps
#RUN apk add --no-cache postgresql-libs && apk add --no-cache gcc musl-dev linux-headers

RUN pip install -r requirements.txt
EXPOSE 5000
COPY . .
CMD ["python", "server.py"]